window.CHEMISTRY_TOPICS = [
  { code: "01.", name: "Redox Reactions", folder: "01b Redox", total: 6 },
  { code: "02.", name: "Atomic Structure", folder: "02 Atomic Structure", total: 6 },
  { code: "03.", name: "Chemical Bonding 1", folder: "03 Chemical Bonding I", total: 18 },
  { code: "04.", name: "The Gaseous State", folder: "04 Gaseous State", total: 6 },
  { code: "05a.", name: "Chemical Energetics 1", folder: "05a Energetics I", total: 5 },
  { code: "05b.", name: "Chemical Energetics 2", folder: "05b Energetics II", total: 3 },
  { code: "06.", name: "Reaction Kinetics", folder: "06 Kinetics", total: 13 },
  { code: "07.", name: "Chemical Equilibria", folder: "07 Chemical Equilibrum", total: 4 },
  { code: "08.", name: "Chemical Bonding (II)", folder: "08 Chemical Bonding II", total: 5 },
  { code: "09.", name: "Introduction to Organic Chemistry", folder: "09 Intro to Organic Chemistry", total: 9 },
  { code: "10.", name: "Alkanes", folder: "10 Alkanes", total: 5 },
  { code: "11.", name: "Alkenes", folder: "11 Alkenes", total: 12 },
  { code: "12a.", name: "Periodic Table (I)", folder: "12 Periodic Table I", total: 7 },
  { code: "12b.", name: "Periodic Table (II)", folder: "13 Periodic Table II", total: 10 },
  { code: "13.", name: "Arenes", folder: "14 Arene", total: 6 },
  { code: "14.", name: "Halogen Derivatives", folder: "16 RX", total: 7 },
  { code: "15.", name: "Acid-Base Equilibria", folder: "15 Acid base", total: 11 },
  { code: "16.", name: "Solubility Equilibria", folder: "21 Solubility Eqm", total: 7 },
  { code: "17.", name: "Hydroxy Compounds", folder: "17 ROH", total: 4 },
  { code: "18.", name: "Carbonyl Compounds", folder: "18 Carbonyl", total: 5 },
  { code: "19.", name: "Carboxylic Acids and Derivatives", folder: "19 Carboxylic acids", total: 4 },
  { code: "20.", name: "Nitrogen Compounds", folder: "20 Nitrogen Compounds", total: 4 },
  { code: "21.", name: "Polymers", folder: "24 Polymers", total: 4 },
  { code: "22a.", name: "Electrochemistry I", folder: "22a Electrochem 1", total: 8 },
  { code: "22b.", name: "Electrochemistry II", folder: "22b Electrochem 2", total: 8 },
  { code: "23.", name: "Transition Elements", folder: "23 Transition Elements", total: 6 }
];
